# Generated by Django 4.0.6 on 2025-04-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_tblpurchaseentry_excise_duty_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchasereturn',
            name='excise_duty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
